Adding Sponsorship section to About Page- issue 78
GWC-UNCC/Girls-Who-Code-at-UNCC pull request #138
Opened 2022-03-20 02:22 UTC by DeneLogan

I put added the sponsorship to the params in the config. Let me know if that actually needs to be somewhere else; I figured a yoml file wouldn't be correct in this case! thanks

2022-03-28 18:56 UTC, bluelotus03 requested changes

2022-03-28 18:56 UTC, bluelotus03 commented on config.toml
> +  comingSoon = "<Coming Soon!>"
Instead of a param in the config file, this should be in a `data/sponsorship.yml` file to stay consistent with other sections of the about page.

2022-03-28 18:56 UTC, bluelotus03 commented on layouts/partials/sponsorship.html
> +{{ with .Site.Params.sponsorship }}
Going off of the previous comment, that would change from `.Site.Params.sponsorship` to `.Site.Data.sponsorship`

2022-03-28 18:56 UTC, bluelotus03 commented on layouts/partials/sponsorship.html
> +            <h3>{{ .comingSoon }}</h3>
It might be good to call `.comingSoon` something like `.sectionText` since it won't always be the words "coming soon".

2022-04-04 17:53 UTC, DeneLogan commented on config.toml
> +  comingSoon = "<Coming Soon!>"
Updated ~

2022-04-04 17:53 UTC, DeneLogan commented on layouts/partials/sponsorship.html
> +{{ with .Site.Params.sponsorship }}
Updated ~

2022-04-04 17:53 UTC, DeneLogan commented on layouts/partials/sponsorship.html
> +            <h3>{{ .comingSoon }}</h3>
Updated ~

2022-04-04 18:16 UTC, bluelotus03 approved these changes
Looks good!

2022-04-04 18:16 UTC, bluelotus03 commented on layouts/partials/sponsorship.html
> +{{ with .Site.Params.sponsorship }}
It looks like this still has "Site. Params," I will edit it real quick though then should be good to go!
![image](https://user-images.githubusercontent.com/25125692/161606121-71acbd4a-274f-4d4d-896b-50ce2d4bc8f4.png)

2022-04-04 18:18 UTC, bluelotus03 commented
Also swapped order of the partials in `/about/list.html`
Make sure the partials are in the order they should appear on the page. Sponsor Us should be below Membership and Partnership sections. It's good to make changes and run the site locally to ensure it looks right before submitting. 
Otherwise, nice job!

2022-04-04 18:19 UTC, merged