Updated info for FAQ section
GWC-UNCC/Girls-Who-Code-at-UNCC pull request #151
Opened 2022-04-08 05:21 UTC by mariamconde

2022-04-11 19:43 UTC, bluelotus03 requested changes
Awesome job ranging through the points for questions! 
Now we need to add the answers to the questions and the accordion for this issue to be complete. I will add some more resources to the doc and talk a bit about Bootstrap today and that will help with this. 

Then you can continue making changes and pushing them to your branch, and it will automatically update the PR here. So you won't have to make a new one. That way you can comment and tag me with "@bluelotus03" to let me know when you're done making updates. 

If you have any questions, just lemme know. Nice job!

2022-04-17 04:37 UTC, mariamconde commented
@bluelotus03 
I left the answers blank because I wasn't sure what to exactly write in there, but once you let me know I can easily add it!

2022-04-18 05:04 UTC, bluelotus03 approved these changes
Awesome job using Bootstrap! 
I left comments on the restructuring I did and why. Let me know if you have any questions on these!

2022-04-18 05:04 UTC, bluelotus03 commented on layouts/partials/faqs.html
> +                    <p>{{ .question1 }}</p>
Instead of ranging, when they are individual points, you can just list their label (such as question1, answer1, etc). Ranging is for if there are multiple items within that label. I relabeled these and will mention more on this in the faqs.yml file

2022-04-18 05:04 UTC, bluelotus03 commented on data/faqs.yml
> +question1: "What are the requirements for membership?"
Labeled these by question number instead of topic because in the future, there could be more than 1 question on a similar topic. Also moved these from the `call-to-action.yml` to an `faqs.yml` because the CTA is what is in the pic below, so we want the FAQs as a separate thing. 
![image](https://user-images.githubusercontent.com/25125692/163757332-7dbd80c6-0b78-47d1-9ee1-0fa8e1a39e01.png)

2022-04-18 05:08 UTC, bluelotus03 commented
@bluelotus03 
I left the answers blank because I wasn't sure what to exactly write in there, but once you let me know I can easily add it!

_Originally posted by @mariamconde in https://github.com/GWC-UNCC/Girls-Who-Code-at-UNCC/issues/151#issuecomment-1100801971_

For this, when we don't have the exact text to use, you can always use Lorem Ipsum text (essentially "dummy text" that you can make a TODO for replacing later)

I did see your comment on replacing later, which is awesome! I moved that comment into the faqs.yml file since that is where the answers will be replaced. I also added "TODO:" in front of it as this is the format we can reuse in our comments, so that we can search for "TODO" and see all the items that we need to finish. 

Let me know if you have any questions on this, and if you have questions on future issues and can reach out before the weekends, I can definitely help!

2022-04-18 05:09 UTC, merged

2022-04-18 05:37 UTC, bluelotus03 commented
I also ended up removing the CSS and meta links because those are already taken care of overall for the website. We also have to stick with the version of Bootstrap that the rest of the site uses, so I had to updated some of the html to match the 4.6 version. When there are multiple ones, it breaks the styling of the about page. 

It will definitely need more styling, but that will be for the styling issue for the FAQs.