"Adding Calendar Text Section"
GWC-UNCC/Girls-Who-Code-at-UNCC pull request #152
Opened 2022-04-10 19:04 UTC by DeneLogan

2022-04-10 19:48 UTC, DeneLogan commented
I was having issues figuring out how to add the links to this page, so I left it as a To-Do.

2022-04-11 19:56 UTC, bluelotus03 requested changes
Looking great! 
We will talk a bit more about linking text today to help with finalizing this issue. 

Then you can continue making changes and pushing them to your branch, and it will automatically update the PR here. So you won't have to make a new one. That way you can comment and tag me with "@bluelotus03" to let me know when you're done making updates.

If you have any questions, just lemme know. Awesome job!

2022-04-11 19:56 UTC, bluelotus03 commented on data/calendar.yml
> +calendar_notes  :
For simplicity of upkeep, I think the "Virtual" and "In-person" sections can be set up the same way you have the "Main Events one, where they are their own sections.

2022-04-14 04:46 UTC, DeneLogan commented on data/calendar.yml
> +calendar_notes  :
@bluelotus03 All done :)!

2022-04-14 19:54 UTC, bluelotus03 commented on data/calendar.yml
> +calendar_notes  :
Awesome job!

2022-04-14 19:54 UTC, bluelotus03 approved these changes
Looks great!

2022-04-14 19:54 UTC, merged