issue/home/quote-section/87
GWC-UNCC/Girls-Who-Code-at-UNCC pull request #153
Opened 2022-04-11 19:15 UTC by zshawar

Added testimonial carousel

2022-04-11 20:06 UTC, bluelotus03 requested changes
Added a couple notes, but overall looking good, nice job!

2022-04-11 20:06 UTC, bluelotus03 commented on layouts/partials/testimonial.html
> +
There seems to be a blank section initially before rotating to the first one.
![image](https://user-images.githubusercontent.com/25125692/162821842-c55d18d8-d3db-415a-a9a2-8950fcf3d62e.png)

Is there a way to remove the extra spacing up top?
![image](https://user-images.githubusercontent.com/25125692/162821982-705905ea-d87d-458e-a5b1-13ac687ac275.png)

And it may be blending in, but are there arrows for going left and right? I think rn it's auto-scrolling

2022-04-11 20:53 UTC, zshawar commented on layouts/partials/testimonial.html
> +
- Carousels need to have one slide with an "active" class. So before the loop, we need something with that class. Right now I left it as a cover image. It can either be changed to a different image that has a unique look and feel and lets the users know it's the testimonial section or we can add a user's testimonial outside of the loop to be that first active slide. There might be another way as well to work around this but I could not find other solutions.

- I will need to double-check the arrows. I will go back through the bootstrap documentation and see what it is missing. It might be blending in but I will make sure they are there.

- The space above is most likely from the background image I am temporarily using until we create the background we want.

2022-04-17 02:23 UTC, zshawar commented
@bluelotus03 I fixed this section using the link you sent me to https://bootstrapious.com/. The only part that I do not think is fully functioning is the lines at the bottom to switch slides. It will only do the ones we mark in the code but if six people give testimonials then there would be 6 of those lines. It might be better to just keep the arrows and get rid of the lines under the quotes.

2022-04-18 05:42 UTC, bluelotus03 commented
@zshawar In response to: https://github.com/GWC-UNCC/Girls-Who-Code-at-UNCC/pull/153#issuecomment-1100789344

I agree, I think we don't need lines, just arrows. 

This looks great, awesome job!

2022-04-18 05:44 UTC, bluelotus03 approved these changes
Awesome job!

2022-04-18 05:45 UTC, merged