issue/home/main-section/97
GWC-UNCC/Girls-Who-Code-at-UNCC pull request #154
Opened 2022-04-11 19:16 UTC by zshawar

Added sponsors section to home

2022-04-11 20:12 UTC, bluelotus03 requested changes
Looks awesome! 
I just left one comment on linking the logos and then I think this issue will be good to go.

You can make that change and push it to your branch for this issue, and it will automatically update the PR here. So you won't have to make a new one. That way you can comment and tag me with "@bluelotus03" to let me know when you're done making updates.

2022-04-11 20:12 UTC, bluelotus03 commented on layouts/partials/sponsors.html
> +            <img src="{{ .image | absURL }}" alt="sponsor-logo">
One thing I forgot to put in the issue was having the logos link to the partner's website. Can you add that?

Here's a section for reference for adding linked images from the web team guide that could help too: 
![image](https://user-images.githubusercontent.com/25125692/162823606-9054b5e7-c007-4b0c-873c-4ccf9c909124.png)

2022-04-11 20:48 UTC, zshawar commented
@bluelotus03 I committed new changes with the added links.

2022-04-16 20:51 UTC, zshawar commented
@bluelotus03

2022-04-18 06:17 UTC, bluelotus03 requested changes
This looks great! 
I just made a couple comments with images to swap and the UNCC AOE website link

2022-04-18 06:17 UTC, bluelotus03 commented on data/sponsors.yml
> +  - image   : images/sponsors/acmw-logo.png
We can make it white if the dark blue doesn't show up right or if the others are all white when we do the styling part.

2022-04-18 06:27 UTC, bluelotus03 approved these changes
Went ahead and made the changes to help with time and since I had the image files. 
Otherwise, looks great!

2022-04-18 06:27 UTC, bluelotus03 commented on data/partners.yml
> +  - image   : images/partners/AOE-logo.png
Updated logo and link

2022-04-18 06:27 UTC, bluelotus03 commented on data/partners.yml
> +  - image   : images/partners/ACMW-logo.png
Updated logo

2022-04-18 06:27 UTC, bluelotus03 commented on layouts/index.html
> +
renamed sponsors --> partners

2022-04-18 06:27 UTC, bluelotus03 commented on layouts/partials/partners.html
> +{{ with .Site.Data.partners}}
renamed sponsors --> partners

2022-04-18 06:28 UTC, merged